-- FrameViewer.lua
-- Auto-generated by live_stream.py
-- Paste into a LocalScript inside StarterPlayerScripts
 
local Players       = game:GetService("Players")
local RunService    = game:GetService("RunService")
local HttpService   = game:GetService("HttpService")
 
local player     = Players.LocalPlayer
local playerGui  = player:WaitForChild("PlayerGui")
 
-- ===== SETTINGS (must match Python script) =====
local RAW_BASE      = "https://raw.githubusercontent.com/palachpalach18-tech/roblox-live/main"
local FRAME_BUFFER  = 60
local FPS           = 1
local POLL_INTERVAL = 2        -- seconds between manifest checks
local LOCAL_DIR     = "rblx_live"
local LAYER_COUNT   = 5        -- ImageLabel layers for smooth overlap
 
local FRAME_TIME    = 1 / FPS
 
-- ===== HTTP helper (supports executors and plain HttpGet) =====
local function httpGet(url)
    local ok, result
    if syn and syn.request then
        ok, result = pcall(syn.request, { Url = url, Method = "GET" })
    elseif http_request then
        ok, result = pcall(http_request, { Url = url, Method = "GET" })
    elseif request then
        ok, result = pcall(request, { Url = url, Method = "GET" })
    else
        ok, result = pcall(function()
            return { StatusCode = 200, Body = game:HttpGet(url) }
        end)
    end
    if ok and result and result.StatusCode == 200 then
        return true, result.Body
    end
    return false, nil
end
 
-- ===== File system =====
if not isfolder(LOCAL_DIR) then
    makefolder(LOCAL_DIR)
end
 
-- ===== GUI =====
local screenGui = Instance.new("ScreenGui")
screenGui.Name           = "LiveViewer"
screenGui.ResetOnSpawn   = false
screenGui.IgnoreGuiInset = true
screenGui.Parent         = playerGui
 
-- Stack of ImageLabels for smooth layer swapping
local layers = table.create(LAYER_COUNT)
for i = 1, LAYER_COUNT do
    local lbl = Instance.new("ImageLabel")
    lbl.Size                  = UDim2.fromOffset(512, 512)
    lbl.Position              = UDim2.fromScale(0.5, 0.5)
    lbl.AnchorPoint           = Vector2.new(0.5, 0.5)
    lbl.BackgroundTransparency = 1
    lbl.BorderSizePixel       = 0
    lbl.ScaleType             = Enum.ScaleType.Fit
    lbl.ZIndex                = i
    lbl.Parent                = screenGui
    layers[i] = lbl
end
 
local statusLabel = Instance.new("TextLabel")
statusLabel.Size                 = UDim2.fromOffset(500, 24)
statusLabel.Position             = UDim2.new(0.5, -250, 0, 8)
statusLabel.BackgroundTransparency = 1
statusLabel.TextColor3           = Color3.fromRGB(255, 255, 0)
statusLabel.TextStrokeTransparency = 0
statusLabel.Font                 = Enum.Font.Code
statusLabel.TextSize             = 16
statusLabel.Text                 = "Connecting to live feed..."
statusLabel.ZIndex               = 200
statusLabel.Parent               = screenGui
 
-- ===== Asset URI cache (slot -> rbxasset URI) =====
local assetCache  = {}
local TOP_Z       = LAYER_COUNT + 10
 
local function layerFor(slot)
    return ((slot - 1) % LAYER_COUNT) + 1
end
 
local function loadAsset(slot)
    if assetCache[slot] then return assetCache[slot] end
    local path = LOCAL_DIR .. "/f" .. slot .. ".jpg"
    if isfile(path) then
        local ok, uri = pcall(getcustomasset, path)
        if ok and uri then
            assetCache[slot] = uri
            return uri
        end
    end
    return nil
end
 
local function showSlot(slot)
    local uri = loadAsset(slot)
    if not uri then return end
    local lyr = layers[layerFor(slot)]
    lyr.Image  = uri
    lyr.ZIndex = TOP_Z
    -- Push previous layer behind
    for i, l in ipairs(layers) do
        if l ~= lyr then
            l.ZIndex = i
        end
    end
end
 
-- ===== Frame downloader =====
local downloaded = {}   -- [slot] = true
 
local function downloadFrame(slot)
    if downloaded[slot] then return end
    local url  = RAW_BASE .. "/frames/f" .. slot .. ".jpg"
    local path = LOCAL_DIR .. "/f" .. slot .. ".jpg"
    local ok, body = httpGet(url)
    if ok and body and #body > 0 then
        writefile(path, body)
        assetCache[slot] = nil   -- force re-load via getcustomasset
        downloaded[slot] = true
    end
end
 
-- ===== Manifest poller =====
local serverTotal  = 0
local serverSlot   = 1
local lastPoll     = -math.huge
 
local function pollManifest()
    local now = os.clock()
    if now - lastPoll < POLL_INTERVAL then return end
    lastPoll = now
 
    local ok, body = httpGet(RAW_BASE .. "/manifest.json")
    if not ok or not body then return end
 
    local ok2, data = pcall(HttpService.JSONDecode, HttpService, body)
    if not ok2 or type(data) ~= "table" then return end
 
    serverTotal = tonumber(data.total) or serverTotal
    serverSlot  = tonumber(data.slot)  or serverSlot
 
    -- Pre-download the next few slots
    for ahead = 0, math.min(LAYER_COUNT, FRAME_BUFFER - 1) do
        local s = ((serverSlot - 1 + ahead) % FRAME_BUFFER) + 1
        task.spawn(downloadFrame, s)
    end
end
 
-- ===== Playback =====
local currentSlot      = 1
local nextSwitchTime   = os.clock() + FRAME_TIME
local fpsCounter       = 0
local fpsWindowStart   = os.clock()
 
-- Kick off background download of all slots on startup
for s = 1, FRAME_BUFFER do
    task.spawn(downloadFrame, s)
end
 
local conn
conn = RunService.Heartbeat:Connect(function()
    if not screenGui.Parent then
        conn:Disconnect()
        return
    end
 
    -- Periodically sync with server
    pollManifest()
 
    local now = os.clock()
    if now < nextSwitchTime then return end
 
    -- Advance frame(s) to stay on schedule
    local prevSlot = currentSlot
    while now >= nextSwitchTime do
        nextSwitchTime += FRAME_TIME
        currentSlot    = (currentSlot % FRAME_BUFFER) + 1
        fpsCounter    += 1
    end
 
    -- Pre-fetch next slot
    task.spawn(downloadFrame, (currentSlot % FRAME_BUFFER) + 1)
 
    -- Display
    showSlot(currentSlot)
 
    -- FPS display
    local now2 = os.clock()
    if now2 - fpsWindowStart >= 1 then
        statusLabel.Text = string.format(
            "LIVE  |  %d fps  |  server frame %d  |  slot %d/%d",
            fpsCounter, serverTotal, currentSlot, FRAME_BUFFER
        )
        fpsCounter      = 0
        fpsWindowStart  = now2
    end
end)
