-- FrameViewer.lua  (auto-generated by live_stream.py)
-- LocalScript inside StarterPlayerScripts
-- Requires executor: http_request/syn.request, writefile, getcustomasset

local Players     = game:GetService("Players")
local RunService  = game:GetService("RunService")
local HttpService = game:GetService("HttpService")

local player    = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local RAW_BASE      = "https://raw.githubusercontent.com/palachpalach18-tech/roblox-live/main"
local FRAME_BUFFER  = 10
local FPS           = 1
local POLL_INTERVAL = 1
local TMP_DIR       = "live_tmp"
local PREFETCH      = 3
local FRAME_TIME    = 1 / FPS

local function httpGet(url)
    local ok, result
    if syn and syn.request then
        ok, result = pcall(syn.request, { Url = url, Method = "GET" })
    elseif http_request then
        ok, result = pcall(http_request, { Url = url, Method = "GET" })
    elseif request then
        ok, result = pcall(request, { Url = url, Method = "GET" })
    else
        ok, result = pcall(function() return { StatusCode = 200, Body = game:HttpGet(url) } end)
    end
    if ok and result and result.StatusCode == 200 then return true, result.Body end
    return false, ""
end

if not isfolder(TMP_DIR) then makefolder(TMP_DIR) end

local screenGui = Instance.new("ScreenGui")
screenGui.Name, screenGui.ResetOnSpawn, screenGui.IgnoreGuiInset = "LiveViewer", false, true
screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
screenGui.Parent = playerGui

local display = Instance.new("ImageLabel")
display.Size = UDim2.fromOffset(512, 512)
display.Position = UDim2.fromScale(0.5, 0.5)
display.AnchorPoint = Vector2.new(0.5, 0.5)
display.BackgroundColor3 = Color3.fromRGB(0,0,0)
display.BackgroundTransparency = 0
display.BorderSizePixel = 0
display.ScaleType = Enum.ScaleType.Fit
display.ZIndex = 1
display.Parent = screenGui

local dbg = Instance.new("TextLabel")
dbg.Size = UDim2.new(1, 0, 0, 80)
dbg.Position = UDim2.fromOffset(0, 0)
dbg.BackgroundColor3 = Color3.fromRGB(0,0,0)
dbg.BackgroundTransparency = 0.5
dbg.TextColor3 = Color3.fromRGB(255,255,0)
dbg.TextStrokeTransparency = 0
dbg.Font = Enum.Font.Code
dbg.TextSize = 13
dbg.TextXAlignment = Enum.TextXAlignment.Left
dbg.TextYAlignment = Enum.TextYAlignment.Top
dbg.Text = "Starting..."
dbg.ZIndex = 200
dbg.Parent = screenGui

-- slot_version[slot] = serverTotal at time of last write
local slot_version = {}
for s = 1, FRAME_BUFFER do slot_version[s] = 0 end

local function slotPath(slot)
    return TMP_DIR .. "/s" .. slot .. "_v" .. (slot_version[slot] or 0) .. ".jpg"
end

local serverTotal  = 0
local serverSlot   = 1
local lastPoll     = -math.huge
local manifestOk   = false

local function pollManifest()
    local now = os.clock()
    if now - lastPoll < POLL_INTERVAL then return end
    lastPoll = now
    local ok, body = httpGet(RAW_BASE .. "/manifest.json")
    if not ok or body == "" then dbg.Text = "manifest FAILED — check RAW_BASE\n" .. RAW_BASE return end
    local ok2, data = pcall(HttpService.JSONDecode, HttpService, body)
    if not ok2 or type(data) ~= "table" then dbg.Text = "manifest parse FAILED" return end
    serverTotal = tonumber(data.total) or serverTotal
    serverSlot  = tonumber(data.slot)  or serverSlot
    manifestOk  = true
end

local downloading = {}

local function fetchSlot(slot)
    if downloading[slot] then return end
    -- Re-fetch if server has written a newer frame to this slot
    local needed = serverTotal - ((serverSlot - slot + FRAME_BUFFER) % FRAME_BUFFER)
    if needed <= slot_version[slot] then return end
    downloading[slot] = true
    task.spawn(function()
        local url = RAW_BASE .. "/frames/f" .. slot .. ".jpg"
        local ok, body = httpGet(url)
        if ok and body and #body > 200 then
            local path = TMP_DIR .. "/s" .. slot .. "_v" .. serverTotal .. ".jpg"
            writefile(path, body)
            slot_version[slot] = serverTotal
        end
        downloading[slot] = false
    end)
end

local playSlot       = 1
local nextSwitchTime = os.clock() + FRAME_TIME
local fpsCounter     = 0
local fpsWindowStart = os.clock()
local lastServerSlot = -1

-- Spin until manifest loads
local t0 = os.clock()
repeat pollManifest() task.wait(0.2) until manifestOk or os.clock()-t0 > 10
if manifestOk then playSlot = serverSlot else dbg.Text = "Could not reach manifest after 10s" end

for i = 0, PREFETCH do
    fetchSlot(((serverSlot - 1 + i) % FRAME_BUFFER) + 1)
end

local conn
conn = RunService.Heartbeat:Connect(function()
    if not screenGui.Parent then conn:Disconnect() return end

    pollManifest()

    for i = 0, PREFETCH do
        fetchSlot(((playSlot - 1 + i) % FRAME_BUFFER) + 1)
    end

    local now = os.clock()
    if now < nextSwitchTime then return end
    nextSwitchTime = now + FRAME_TIME

    -- Only advance when the server has a new slot
    if serverSlot == lastServerSlot then return end
    playSlot       = serverSlot
    lastServerSlot = serverSlot

    local path = slotPath(playSlot)
    if isfile(path) then
        local ok, uri = pcall(getcustomasset, path)
        if ok and uri and uri ~= "" then
            display.Image = uri
            fpsCounter += 1
        else
            dbg.Text = "getcustomasset FAILED: " .. tostring(path)
        end
    else
        dbg.Text = "waiting for slot " .. playSlot
    end

    local now2 = os.clock()
    if now2 - fpsWindowStart >= 1 then
        dbg.Text = string.format(
            "LIVE | fps=%d | total=%d | slot=%d | img=%s",
            fpsCounter, serverTotal, serverSlot,
            display.Image ~= "" and "OK" or "empty"
        )
        fpsCounter = 0
        fpsWindowStart = now2
    end
end)
